version: '3.9'
services:
  backend:
    build: ./fitness-tracker-backend
    environment:
      - DB_USER=${DB_USER}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=5000
    ports:
      - "7100:5000"
    depends_on:
      - db

  frontend:
    build: ./fitness-tracker-website
    ports:
      - "4000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:7100

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
